### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by ayophanz** [basicit/lumen-vendor-publish#16]
after running this `php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations" ` I get that error

**Comment by Geowan** [comment]
Am also facing the same issue.

**Comment by parthibd** [comment]
Same here. Doesn't work with clockwork.

**Comment by mabasic** [comment]
I will have to look into this...

**Comment by mabasic** [comment]
I've found a solution for this.

Add this code in your `bootstrap/app.php` file under "Register Service Providers":

```php
if (!function_exists('config_path')) {
    /**
     * Get the configuration path.
     *
     * @param string $path
     * @return string
     */
    function config_path($path = '')
    {
        return app()->configPath($path);
    }
}

$app->register(Spatie\MediaLibrary\MediaLibraryServiceProvider::class);
```

Then run:

```
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"
```

Output:

```
$ php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="migrations"
Copied File [/vendor/spatie/laravel-medialibrary/database/migrations/create_media_table.php.stub] To [/database/migrations/2021_09_11_151255_create_media_table.php]
Publishing complete.
```

Tested with `Laravel Framework Lumen (8.2.4) (Laravel Components ^8.0)`.

This works now, but will stop working if I update `VendorPublishCommand` to match the latest Laravel version because of [`VendorTagPublish`](https://github.com/laravel/framework/blob/277c2fbd0cebd2cb194807654d870f4040e288c0/src/Illuminate/Foundation/Events/VendorTagPublished.php) being placed inside `laravel/framework` meaning that you would have to pull entire Laravel framework in your Lumen app just to get that class.

See this line https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Console/VendorPublishCommand.php#L174

I could change the `VendorPublishCommand` to use a copied version of that file, but the listeners for that command will not work.

Related issues, PRs, etc. : 
- https://github.com/laravelista/lumen-vendor-publish/issues/5
- https://github.com/laravelista/lumen-vendor-publish/pull/10
- https://github.com/spatie/laravel-medialibrary/issues/668

This means that I will archive this package for good.

If you need to publish resources, you can copy the files manually or use Laravel instead.
